export const ErrorCodes = {
	UNSUPPORTED_CONTENT_TYPE: 'UNSUPPORTED_CONTENT_TYPE',
	NO_LIST: 'NO_LIST',
	NO_USER: 'NO_USER',
	NO_LISTS: 'NO_LISTS',
	INVALID_USER_ID: 'INVALID_USER_ID',
	INVALID_TITLE: 'INVALID_TITLE',
	CORRUPTED: 'CORRUPTED',
	EMAIL_PASSWORD_REQUIRED: 'EMAIL_PASSWORD_REQUIRED',
	USER_EXISTS: 'USER_EXISTS',
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	USER_AND_TITLE_REQUIRED: 'USER_AND_TITLE_REQUIRED',
	USER_IS_NOT_ACTIVATED: 'USER_IS_NOT_ACTIVATED'
};
